CREATE TABLE IF NOT EXISTS `dwd_sd_shipment_detail_df` (
  `delivery_order_num` VARCHAR(100) COMMENT '交货单号',
  `delivery_order_item_num` VARCHAR(100) COMMENT '交货单行号',
  `order_num` VARCHAR(100) COMMENT '销售订单号',
  `order_item_num` VARCHAR(100) COMMENT '销售订单行号',
  `manu_sales_order_num` VARCHAR(100) COMMENT '制造公司销售订单号',
  `order_num_transfer` VARCHAR(100) COMMENT '销售订单号_含抛转',
  `contract_num` VARCHAR(100) COMMENT '合同号（客户采购订单编号）',
  `contract_m_num` VARCHAR(100) COMMENT '母合同号',
  `order_type_code` VARCHAR(100) COMMENT '订单类型编码',
  `order_type_name` VARCHAR(255) COMMENT 'new 订单类型名称',
  `shipment_date` DATETIME COMMENT '出货日期',
  `request_del_date` DATETIME COMMENT '请求交货日期',
  `approval_date` DATETIME COMMENT '订单首次审批日期',
  `create_date` DATETIME COMMENT 'new 订单创建日期',
  `latest_warehousing_date` DATETIME COMMENT '最新入库日期',
  `MSEG` VARCHAR(256),
  `ON` VARCHAR(256) COMMENT 'MSEG',
  `BWART` VARCHAR(256),
  `ZSD068VA` VARCHAR(256),
  `ZSD124VA` VARCHAR(256),
  `ON` VARCHAR(256) COMMENT 'MSEG',
  `BWART` VARCHAR(256),
  `MSEG` VARCHAR(256),
  `BWART` VARCHAR(256),
  `mat_code` VARCHAR(100) COMMENT '物料编码',
  `mat_desc` VARCHAR(255) COMMENT '物料描述',
  `industry_code` VARCHAR(100) COMMENT '产业编码',
  `industry_name` VARCHAR(255) COMMENT '产业描述',
  `product_line_code` VARCHAR(100) COMMENT '产品线编码',
  `product_line_name` VARCHAR(255) COMMENT '产品线描述',
  `product_group_code` VARCHAR(100) COMMENT '产品族编码',
  `product_group_name` VARCHAR(255) COMMENT '产品族描述',
  `product_series_code` VARCHAR(100) COMMENT '产品系列编码',
  `product_series_name` VARCHAR(255) COMMENT '产品系列描述',
  `product_area` DECIMAL(27,8) COMMENT '产品单位面积',
  `product_type` VARCHAR(100) COMMENT '产品类型',
  `industry_type` VARCHAR(100) COMMENT '行业类型',
  `special_stock_flag` VARCHAR(100) COMMENT '特殊库存标识',
  `delivery_address` VARCHAR(255) COMMENT '交货地址',
  `special_stock_name` VARCHAR(100) COMMENT '特殊库存标识名称',
  `factory_code` VARCHAR(100) COMMENT '工厂编码',
  `factory_name` VARCHAR(255) COMMENT '工厂名称',
  `company_code` VARCHAR(100) COMMENT '公司代码',
  `company_name` VARCHAR(255) COMMENT '公司名称',
  `customer_code` VARCHAR(100) COMMENT '客户编码',
  `customer_name` VARCHAR(255) COMMENT '客户名称',
  `sales_person_num` VARCHAR(100) COMMENT 'new 业务员编码',
  `sales_person_name` VARCHAR(255) COMMENT '业务员姓名',
  `sales_dept_code` VARCHAR(100) COMMENT 'new 销售部门编码',
  `sales_dept_name` VARCHAR(255) COMMENT '销售部门名称',
  `employee_dept_code` VARCHAR(100) COMMENT '雇员部门编码',
  `employee_dept_name` VARCHAR(255) COMMENT '雇员部门名称',
  `sales_org_code` VARCHAR(100) COMMENT 'new 销售组织编码',
  `sales_org_name` VARCHAR(255) COMMENT '销售组织名称',
  `sales_group_code` VARCHAR(100) COMMENT 'new 销售组',
  `sales_group_name` VARCHAR(255) COMMENT '销售组名称',
  `sales_channel_code` VARCHAR(100) COMMENT 'new 分销渠道编码',
  `sales_channel_name` VARCHAR(255) COMMENT '分销渠道名称',
  `sales_unit_name` VARCHAR(255) COMMENT 'new 销售战区名称',
  `sales_area_name` VARCHAR(255) COMMENT 'new 销售大区名称',
  `sales_region_name` VARCHAR(255) COMMENT 'new 销售区域名称',
  `customer_country_code` VARCHAR(100) COMMENT '客户所属国家编码',
  `customer_country_name` VARCHAR(255) COMMENT '客户所属国家名称',
  `freight_forwarder` VARCHAR(100) COMMENT '货代',
  `transport_method` VARCHAR(100) COMMENT '运输方式',
  `payment_method` VARCHAR(100) COMMENT '付款方式',
  `embezzle_spot_info` VARCHAR(100) COMMENT '挪用现货信息',
  `is_need_inspection` VARCHAR(100) COMMENT '是否需要验收',
  `is_inspected` VARCHAR(100) COMMENT '是否已验收',
  `LK` VARCHAR(256) COMMENT 'LIKP',
  `distinct` VARCHAR(256) COMMENT 'select',
  `from` VARCHAR(256),
  `JOIN` VARCHAR(256) COMMENT 'LEFT',
  `JOIN` VARCHAR(256) COMMENT 'LEFT',
  `IS` VARCHAR(256) NOT NULL COMMENT 'SFAKN',
  `LEFT` VARCHAR(256) COMMENT ')T',
  `inspection_order_num` VARCHAR(100) COMMENT '验收单号',
  `distinct` VARCHAR(256) COMMENT 'select',
  `from` VARCHAR(256),
  `JOIN` VARCHAR(256) COMMENT 'LEFT',
  `JOIN` VARCHAR(256) COMMENT 'LEFT',
  `IS` VARCHAR(256) NOT NULL COMMENT 'SFAKN',
  `LEFT` VARCHAR(256) COMMENT ')T',
  `VBELN` VARCHAR(256),
  `inspection_invoice_date` DATETIME COMMENT '验收开票日期',
  `trade_terms` VARCHAR(500) COMMENT '贸易条款',
  `warranty_period` VARCHAR(100) COMMENT '质保期',
  `project_text` VARCHAR(500) COMMENT '项目文本',
  `currency` VARCHAR(100) COMMENT '销售订单行币种',
  `cny_exchange_rate` DECIMAL(27,8) COMMENT 'new 汇率（to_CNY）',
  `usd_exchange_rate` DECIMAL(27,8) COMMENT 'new 汇率（to_USD）',
  `M` VARCHAR(256),
  `freight_amt` DECIMAL(27,8) COMMENT 'new 订单运费金额-原币',
  `order_qty` DECIMAL(27,8) COMMENT 'new 订单数量',
  `product_area` DECIMAL(27,8) COMMENT 'new 单位面积（平方米）',
  `order_area` DECIMAL(27,8) COMMENT 'new 订单面积',
  `order_tax_amt` DECIMAL(27,8) COMMENT 'new 订单金额（含运费）_含税-原币',
  `order_tax_cny_amt` DECIMAL(27,8) COMMENT 'new 订单金额（含运费）_含税-CNY',
  `order_tax_usd_amt` DECIMAL(27,8) COMMENT 'new 订单金额（含运费）_含税-USD',
  `order_notax_amt` DECIMAL(27,8) COMMENT 'new 订单金额（含运费）_不含税-原币',
  `order_notax_cny_amt` DECIMAL(27,8) COMMENT 'new 订单金额（含运费）_不含税-CNY',
  `order_notax_usd_amt` DECIMAL(27,8) COMMENT 'new 订单金额（含运费）_不含税-USD',
  `shipment_qty` DECIMAL(27,8) COMMENT 'new 出货数量',
  `VBFA` VARCHAR(256),
  `VBUP` VARCHAR(256),
  `RFMNG` VARCHAR(256),
  `WBSTA` VARCHAR(256),
  `ON` VARCHAR(256) COMMENT 'VBFA',
  `VBUP` VARCHAR(256) COMMENT 'join',
  `VBFA` VARCHAR(256),
  `AND` VARCHAR(256),
  `AND` VARCHAR(256),
  `LIPS` VARCHAR(256),
  `shipment_area` DECIMAL(27,8) COMMENT 'new 出货面积',
  `shipment_tax_amt` DECIMAL(27,8) COMMENT 'new 出货金额（含运费）_含税-原币',
  `shipment_tax_cny_amt` DECIMAL(27,8) COMMENT 'new 出货金额（含运费）_含税-CNY',
  `shipment_tax_usd_amt` DECIMAL(27,8) COMMENT 'new 出货金额（含运费）_含税-USD',
  `shipment_notax_amt` DECIMAL(27,8) COMMENT 'new 出货金额（含运费）_不含税-原币',
  `shipment_notax_cny_amt` DECIMAL(27,8) COMMENT 'new 出货金额（含运费）_不含税-CNY',
  `shipment_notax_usd_amt` DECIMAL(27,8) COMMENT 'new 出货金额（含运费）_不含税-USD',
  `unshipment_qty` DECIMAL(27,8) COMMENT 'new 未出货数量',
  `unshipment_area` DECIMAL(27,8) COMMENT 'new 未出货面积',
  `unshipment_tax_amt` DECIMAL(27,8) COMMENT 'new 未出货金额（含运费）_含税-原币',
  `unshipment_tax_cny_amt` DECIMAL(27,8) COMMENT 'new 未出货金额（含运费）_含税-CNY',
  `unshipment_tax_usd_amt` DECIMAL(27,8) COMMENT 'new 未出货金额（含运费）_含税-USD',
  `unshipment_notax_amt` DECIMAL(27,8) COMMENT 'new 未出货金额（含运费）_不含税-原币',
  `unshipment_notax_cny_amt` DECIMAL(27,8) COMMENT 'new 未出货金额（含运费）_不含税-CNY',
  `unshipment_notax_usd_amt` DECIMAL(27,8) COMMENT 'new 未出货金额（含运费）_不含税-USD',
  `scenario_tag` VARCHAR(100) COMMENT 'new 场景标签',
  `ZSD_SUB` VARCHAR(256),
  `ZSD_SUB` VARCHAR(256),
  `setleaf` VARCHAR(256),
  `vkorg` VARCHAR(256) COMMENT '若某销售订单存在',
  `SELECT` VARCHAR(256),
  `vb` VARCHAR(256),
  `COUNT` VARCHAR(256),
  `zs` VARCHAR(256),
  `vb` VARCHAR(256),
  `FROM` VARCHAR(256),
  `JOIN` VARCHAR(256) COMMENT 'LEFT',
  `IS` VARCHAR(256) NOT NULL COMMENT 'vbeln',
  `AND` VARCHAR(256),
  `insert_dt` DATETIME COMMENT '数仓数据更新时间',
  `source_system` VARCHAR(100) COMMENT '来源系统'
) ENGINE=OLAP
PRIMARY KEY(`LEFT`)
DISTRIBUTED BY HASH(`LEFT`) BUCKETS 10;