CREATE TABLE ods_knowledge_doc_di (
    doc_id VARCHAR(64) NOT NULL COMMENT '文档唯一ID',
    stat_date DATE NOT NULL COMMENT '统计日期(分区字段)',
    doc_title VARCHAR(512) NOT NULL COMMENT '文档标题',
    doc_content TEXT NOT NULL COMMENT '文档内容',
    content_chunks JSON COMMENT '分块后的内容',
    vector_representation JSON COMMENT '向量表示',
    metadata JSON COMMENT '文档元数据',
    source_system VARCHAR(64) NOT NULL COMMENT '来源系统',
    doc_type VARCHAR(32) NOT NULL COMMENT '文档类型(faq/product/manual/news等)',
    doc_format VARCHAR(32) NOT NULL COMMENT '文档格式(text/pdf/html等)',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL COMMENT '更新时间',
    last_accessed DATETIME COMMENT '最后访问时间',
    access_count INT DEFAULT 0 COMMENT '访问次数',
    is_deleted TINYINT(1) DEFAULT 0 COMMENT '是否已删除(0:否,1:是)',
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (doc_id, stat_date),
    KEY idx_doc_title (doc_title(255)),
    KEY idx_source_system (source_system),
    KEY idx_doc_type (doc_type),
    KEY idx_create_time (create_time),
    KEY idx_update_time (update_time)
) COMMENT '外部知识库文档表';