CREATE TABLE IF NOT EXISTS `dws_sd_inventory_detail_di` (
  `dt` VARCHAR(256) COMMENT 'new 日期(分区字段YYYYMMDD）',
  `order_num` VARCHAR(256) COMMENT '销售公司销售订单号',
  `contract_num` VARCHAR(256) COMMENT '客户采购订单编号',
  `order_item_num` VARCHAR(256) COMMENT '订单行项目号',
  `order_type_code` VARCHAR(256) COMMENT '订单类型编码',
  `manu_sales_order_num` VARCHAR(256) COMMENT '制造公司销售订单号',
  `order_num_transfer` VARCHAR(256) COMMENT 'new 销售订单号_含抛转',
  `create_date` VARCHAR(256) COMMENT '订单创建日期',
  `approval_date` VARCHAR(256) COMMENT '订单首次审批日期',
  `newest_date` VARCHAR(256) COMMENT '订单最新日期',
  `contract_need_days` VARCHAR(256) COMMENT '合同需求天数',
  `contract_need_date` VARCHAR(256) COMMENT '合同需求日期',
  `review_del_days` VARCHAR(256) COMMENT '评审交期（天数）',
  `pmc_review_del_date` VARCHAR(256) COMMENT 'PMC评审交期',
  `vbak` VARCHAR(256),
  `request_del_date` VARCHAR(256) COMMENT '预计出货日期',
  `c` VARCHAR(256),
  `f` VARCHAR(256),
  `plan_vl_date` VARCHAR(256),
  `YJCHSJ` VARCHAR(256),
  `vbak` VARCHAR(256),
  `vbak` VARCHAR(256),
  `pmc_change_date` VARCHAR(256) COMMENT 'PMC变更日期',
  `c` VARCHAR(256),
  `f` VARCHAR(256),
  `PMC_CHANGE_DATE` VARCHAR(256),
  `BGHJQ` VARCHAR(256),
  `vbak` VARCHAR(256),
  `vbak` VARCHAR(256),
  `last_receipt_date` VARCHAR(256) COMMENT '最后入库日期',
  `e` VARCHAR(256),
  `ON` VARCHAR(256) COMMENT 'MSEG',
  `BWART` VARCHAR(256),
  `transport_method` VARCHAR(256) COMMENT '运输方式',
  `trade_terms` VARCHAR(256) COMMENT '贸易条款',
  `payment_method` VARCHAR(256) COMMENT '付款方式',
  `need_accept_flag` VARCHAR(256) COMMENT '是否需要验收',
  `sales_org_code` VARCHAR(256) COMMENT '销售组织编码',
  `sales_org_name` VARCHAR(256) COMMENT '销售组织名称',
  `factory_code` VARCHAR(256) COMMENT '工厂编码',
  `factory_name` VARCHAR(256) COMMENT '工厂名称',
  `employee_dept_code` VARCHAR(256) COMMENT '雇员部门编码',
  `employee_dept_name` VARCHAR(256) COMMENT '雇员部门名称',
  `sales_person_num` VARCHAR(256) COMMENT '业务员编码',
  `sales_person_name` VARCHAR(256) COMMENT '业务员姓名',
  `sales_region_code` VARCHAR(256) COMMENT '销售区域编码',
  `sales_area_code` VARCHAR(256) COMMENT '销售大区编码',
  `sales_unit_code` VARCHAR(256) COMMENT '销售战区编码',
  `customer_code` VARCHAR(256) COMMENT '客户编码',
  `customer_name` VARCHAR(256) COMMENT '客户名称',
  `product_type` VARCHAR(256) COMMENT '产品类型',
  `industry_type` VARCHAR(256) COMMENT '行业类型',
  `product_code` VARCHAR(256) COMMENT '产品编码',
  `product_name` VARCHAR(256) COMMENT '产品描述',
  `industry_code` VARCHAR(100) COMMENT '产业编码',
  `industry_name` VARCHAR(100) COMMENT '产业描述',
  `product_line_code` VARCHAR(100) COMMENT '产品线编码',
  `product_line_name` VARCHAR(100) COMMENT '产品线描述',
  `product_group_code` VARCHAR(100) COMMENT '产品族编码',
  `product_group_name` VARCHAR(100) COMMENT '产品族描述',
  `product_series_code` VARCHAR(100) COMMENT '产品系列编码',
  `product_series_name` VARCHAR(100) COMMENT '产品系列描述',
  `product_area` DECIMAL(27,8) COMMENT '产品单位面积',
  `order_line_inv_flag` VARCHAR(256) COMMENT '订单行库存标识',
  `sum` VARCHAR(256),
  `AND` VARCHAR(256),
  `inventory_status` VARCHAR(256) COMMENT '库存状态',
  `e` VARCHAR(256),
  `MSEG` VARCHAR(256),
  `X` VARCHAR(256),
  `order_exec_status` VARCHAR(256) COMMENT '订单执行状态',
  `noship_reason` VARCHAR(256) COMMENT '未出货原因',
  `noship_reason_category` VARCHAR(256) COMMENT '未出货原因类别',
  `cny_exchange_rate` VARCHAR(256) COMMENT '汇率（to_CNY）',
  `usd_exchange_rate` VARCHAR(256) COMMENT '汇率（to_USD）',
  `M` VARCHAR(256),
  `order_qty` VARCHAR(256) COMMENT '订单数量',
  `order_area` VARCHAR(256) COMMENT '订单面积',
  `order_tax_amt` VARCHAR(256) COMMENT '订单金额（含运费）_含税-原币',
  `order_tax_cny_amt` VARCHAR(256) COMMENT '订单金额（含运费）_含税-CNY',
  `order_tax_usd_amt` VARCHAR(256) COMMENT '订单金额（含运费）_含税-USD',
  `order_notax_amt` VARCHAR(256) COMMENT '订单金额（含运费）_不含税-原币',
  `order_notax_cny_amt` VARCHAR(256) COMMENT '订单金额（含运费）_不含税-CNY',
  `order_notax_usd_amt` VARCHAR(256) COMMENT '订单金额（含运费）_不含税-USD',
  `shipment_qty` VARCHAR(256) COMMENT '出货数量',
  `shipment_area` VARCHAR(256) COMMENT '出货面积',
  `shipment_tax_amt` VARCHAR(256) COMMENT '出货金额（含运费）_含税-原币',
  `shipment_tax_cny_amt` VARCHAR(256) COMMENT '出货金额（含运费）_含税-CNY',
  `shipment_tax_usd_amt` VARCHAR(256) COMMENT '出货金额（含运费）_含税-USD',
  `shipment_notax_amt` VARCHAR(256) COMMENT '出货金额（含运费）_不含税-原币',
  `shipment_notax_cny_amt` VARCHAR(256) COMMENT '出货金额（含运费）_不含税-CNY',
  `shipment_notax_usd_amt` VARCHAR(256) COMMENT '出货金额（含运费）_不含税-USD',
  `unshipment_qty` VARCHAR(256) COMMENT '未出货数量',
  `unshipment_area` VARCHAR(256) COMMENT '未出货面积',
  `unshipment_tax_amt` VARCHAR(256) COMMENT '未出货金额（含运费）_含税-原币',
  `unshipment_tax_cny_amt` VARCHAR(256) COMMENT '未出货金额（含运费）_含税-CNY',
  `unshipment_tax_usd_amt` VARCHAR(256) COMMENT '未出货金额（含运费）_含税-USD',
  `unshipment_notax_amt` VARCHAR(256) COMMENT '未出货金额（含运费）_不含税-原币',
  `unshipment_notax_cny_amt` VARCHAR(256) COMMENT '未出货金额（含运费）_不含税-CNY',
  `unshipment_notax_usd_amt` VARCHAR(256) COMMENT '未出货金额（含运费）_不含税-USD',
  `source_system` VARCHAR(256) COMMENT '来源系统',
  `insert_dt` VARCHAR(256) COMMENT '数仓数据更新时间'
) ENGINE=OLAP
DUPLICATE KEY(`dt`)
PARTITION BY RANGE(`dt`) ()
DISTRIBUTED BY HASH(`dt`) BUCKETS 10;